import type { RegistryServer } from './types'

export const MOCK_SERVERS: RegistryServer[] = [
  {
    id: '1',
    org_id: null,
    name: 'Stripe MCP',
    slug: 'stripe-mcp',
    description: 'Official Stripe MCP server. Manage payments, subscriptions, customers and invoices. Create payment links, check transaction status and query your Stripe account — all via natural language.',
    category: 'payments',
    endpoint_url: 'https://mcp.stripe.com',
    auth_type: 'oauth',
    schema_json: null,
    version: '1.0.0',
    is_public: true,
    is_verified: true,
    install_count: 24800,
    rating_avg: 4.9,
    pricing_type: 'free',
    price_monthly: null,
    logo_url: null,
    tags: ['stripe', 'payments', 'subscriptions', 'invoices'],
    github_url: 'https://github.com/stripe/agent-toolkit',
    docs_url: 'https://docs.stripe.com/mcp',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    org_id: null,
    name: 'Notion MCP',
    slug: 'notion-mcp',
    description: 'Official Notion hosted MCP server. Read and write pages, databases and blocks. Your AI agent gets secure access to your workspace — create pages, update databases and search content.',
    category: 'productivity',
    endpoint_url: 'https://mcp.notion.com/mcp',
    auth_type: 'oauth',
    schema_json: null,
    version: '1.0.0',
    is_public: true,
    is_verified: true,
    install_count: 18600,
    rating_avg: 4.8,
    pricing_type: 'free',
    price_monthly: null,
    logo_url: null,
    tags: ['notion', 'productivity', 'notes', 'database'],
    github_url: 'https://github.com/makenotion/notion-mcp-server',
    docs_url: 'https://developers.notion.com/docs/mcp',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    org_id: null,
    name: 'GitHub MCP',
    slug: 'github-mcp',
    description: 'Official GitHub MCP server via GitHub Copilot. Read repos, create issues, manage pull requests, search code and trigger Actions workflows — all from your AI agent.',
    category: 'devtools',
    endpoint_url: 'https://api.githubcopilot.com/mcp/',
    auth_type: 'oauth',
    schema_json: null,
    version: '1.0.0',
    is_public: true,
    is_verified: true,
    install_count: 31200,
    rating_avg: 4.9,
    pricing_type: 'free',
    price_monthly: null,
    logo_url: null,
    tags: ['github', 'git', 'issues', 'pull-requests', 'ci-cd'],
    github_url: 'https://github.com/github/github-mcp-server',
    docs_url: 'https://docs.github.com/en/copilot/using-github-copilot/using-github-copilot-in-your-ide',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    org_id: null,
    name: 'Zapier MCP',
    slug: 'zapier-mcp',
    description: 'Connect your AI agent to 8,000+ apps via Zapier. Trigger Zaps, run automations and interact with any app in the Zapier ecosystem — Gmail, Slack, Salesforce, HubSpot and more.',
    category: 'productivity',
    endpoint_url: 'https://mcp.zapier.com/',
    auth_type: 'oauth',
    schema_json: null,
    version: '1.0.0',
    is_public: true,
    is_verified: true,
    install_count: 15400,
    rating_avg: 4.7,
    pricing_type: 'free',
    price_monthly: null,
    logo_url: null,
    tags: ['zapier', 'automation', 'integrations', 'workflows'],
    github_url: 'https://github.com/zapier/zapier-mcp',
    docs_url: 'https://zapier.com/mcp',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '5',
    org_id: null,
    name: 'Supabase MCP',
    slug: 'supabase-mcp',
    description: 'Official Supabase remote MCP server. Query your database, manage tables, call Edge Functions and browse storage — your AI agent gets full access to your Supabase project.',
    category: 'devtools',
    endpoint_url: 'https://mcp.supabase.com/mcp',
    auth_type: 'oauth',
    schema_json: null,
    version: '1.0.0',
    is_public: true,
    is_verified: true,
    install_count: 9800,
    rating_avg: 4.8,
    pricing_type: 'free',
    price_monthly: null,
    logo_url: null,
    tags: ['supabase', 'database', 'postgres', 'backend'],
    github_url: 'https://github.com/supabase-community/supabase-mcp',
    docs_url: 'https://supabase.com/docs/guides/getting-started/mcp',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '6',
    org_id: null,
    name: 'Shopify MCP',
    slug: 'shopify-mcp',
    description: 'Official Shopify Dev MCP. Manage products, orders, customers and inventory. Includes GraphQL schema introspection, theme validation and Shopify docs search for AI-powered development.',
    category: 'ecommerce',
    endpoint_url: 'https://mcp.mcpify.app/servers/shopify-mcp',
    auth_type: 'api_key',
    schema_json: null,
    version: '1.2.0',
    is_public: true,
    is_verified: true,
    install_count: 12400,
    rating_avg: 4.8,
    pricing_type: 'free',
    price_monthly: null,
    logo_url: null,
    tags: ['shopify', 'ecommerce', 'orders', 'products'],
    github_url: 'https://github.com/Shopify/dev-mcp',
    docs_url: 'https://shopify.dev/docs/api/mcp',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '7',
    org_id: null,
    name: 'HubSpot MCP',
    slug: 'hubspot-mcp',
    description: 'Manage contacts, deals and companies in HubSpot. AI agent can create contacts, update deal stages, log activities and query your CRM data in real time.',
    category: 'crm',
    endpoint_url: 'https://mcp.mcpify.app/servers/hubspot-mcp',
    auth_type: 'api_key',
    schema_json: null,
    version: '1.1.0',
    is_public: true,
    is_verified: false,
    install_count: 7300,
    rating_avg: 4.5,
    pricing_type: 'free',
    price_monthly: null,
    logo_url: null,
    tags: ['hubspot', 'crm', 'contacts', 'deals'],
    github_url: null,
    docs_url: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '8',
    org_id: null,
    name: 'hirelang MCP',
    slug: 'hirelang-mcp',
    description: 'AI-powered candidate screening via voice. Create screening calls, get transcripts, scores and compare candidates against job requirements automatically.',
    category: 'hr',
    endpoint_url: 'https://mcp.mcpify.app/servers/hirelang-mcp',
    auth_type: 'api_key',
    schema_json: null,
    version: '1.0.0',
    is_public: true,
    is_verified: true,
    install_count: 3200,
    rating_avg: 4.7,
    pricing_type: 'paid',
    price_monthly: 2900,
    logo_url: null,
    tags: ['hr', 'recruiting', 'screening', 'candidates'],
    github_url: null,
    docs_url: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
]
