import type { RegistryServer } from './types'

export const MOCK_SERVERS: RegistryServer[] = [
  {
    id: '1',
    org_id: null,
    name: 'Shopify MCP',
    slug: 'shopify-mcp',
    description: 'Full Shopify access for AI agents. Manage products, orders, customers and inventory. Your agent can search products, create orders and check stock levels.',
    category: 'ecommerce',
    endpoint_url: 'https://mcp.mcpify.app/servers/shopify-mcp',
    auth_type: 'api_key',
    schema_json: null,
    version: '1.2.0',
    is_public: true,
    is_verified: true,
    install_count: 12400,
    rating_avg: 4.9,
    pricing_type: 'free',
    price_monthly: null,
    logo_url: null,
    tags: ['shopify', 'ecommerce', 'orders', 'products'],
    github_url: null,
    docs_url: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    org_id: null,
    name: 'Stripe MCP',
    slug: 'stripe-mcp',
    description: 'Payments, subscriptions and invoices for AI agents. Create payment links, check transaction status, manage customers and subscriptions.',
    category: 'payments',
    endpoint_url: 'https://mcp.mcpify.app/servers/stripe-mcp',
    auth_type: 'api_key',
    schema_json: null,
    version: '2.0.1',
    is_public: true,
    is_verified: true,
    install_count: 9100,
    rating_avg: 4.8,
    pricing_type: 'free',
    price_monthly: null,
    logo_url: null,
    tags: ['stripe', 'payments', 'subscriptions', 'invoices'],
    github_url: null,
    docs_url: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    org_id: null,
    name: 'GitHub MCP',
    slug: 'github-mcp',
    description: 'Full GitHub access for AI agents. Read repos, create issues, manage PRs, search code and trigger workflows.',
    category: 'devtools',
    endpoint_url: 'https://mcp.mcpify.app/servers/github-mcp',
    auth_type: 'oauth',
    schema_json: null,
    version: '3.1.0',
    is_public: true,
    is_verified: true,
    install_count: 8700,
    rating_avg: 4.9,
    pricing_type: 'free',
    price_monthly: null,
    logo_url: null,
    tags: ['github', 'git', 'issues', 'pull-requests'],
    github_url: null,
    docs_url: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '4',
    org_id: null,
    name: 'Notion MCP',
    slug: 'notion-mcp',
    description: 'Read and write Notion pages, databases and blocks. Your AI agent can create pages, update databases and search across your workspace.',
    category: 'productivity',
    endpoint_url: 'https://mcp.mcpify.app/servers/notion-mcp',
    auth_type: 'oauth',
    schema_json: null,
    version: '1.2.1',
    is_public: true,
    is_verified: false,
    install_count: 5200,
    rating_avg: 4.6,
    pricing_type: 'free',
    price_monthly: null,
    logo_url: null,
    tags: ['notion', 'productivity', 'notes', 'database'],
    github_url: null,
    docs_url: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '5',
    org_id: null,
    name: 'Slack MCP',
    slug: 'slack-mcp',
    description: 'Send messages, read channels, manage users and search Slack history. AI agent can post updates and monitor conversations.',
    category: 'communication',
    endpoint_url: 'https://mcp.mcpify.app/servers/slack-mcp',
    auth_type: 'oauth',
    schema_json: null,
    version: '1.4.0',
    is_public: true,
    is_verified: true,
    install_count: 6800,
    rating_avg: 4.7,
    pricing_type: 'free',
    price_monthly: null,
    logo_url: null,
    tags: ['slack', 'messaging', 'channels', 'notifications'],
    github_url: null,
    docs_url: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '6',
    org_id: null,
    name: 'HubSpot MCP',
    slug: 'hubspot-mcp',
    description: 'Manage contacts, deals and companies in HubSpot. AI agent can create contacts, update deal stages and log activities.',
    category: 'crm',
    endpoint_url: 'https://mcp.mcpify.app/servers/hubspot-mcp',
    auth_type: 'api_key',
    schema_json: null,
    version: '1.1.0',
    is_public: true,
    is_verified: false,
    install_count: 3400,
    rating_avg: 4.5,
    pricing_type: 'free',
    price_monthly: null,
    logo_url: null,
    tags: ['hubspot', 'crm', 'contacts', 'deals'],
    github_url: null,
    docs_url: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '7',
    org_id: null,
    name: 'Google Analytics MCP',
    slug: 'ga4-mcp',
    description: 'Query GA4 analytics data with natural language. Get traffic reports, conversion rates, user behavior and custom metrics.',
    category: 'analytics',
    endpoint_url: 'https://mcp.mcpify.app/servers/ga4-mcp',
    auth_type: 'oauth',
    schema_json: null,
    version: '1.0.3',
    is_public: true,
    is_verified: false,
    install_count: 4100,
    rating_avg: 4.4,
    pricing_type: 'free',
    price_monthly: null,
    logo_url: null,
    tags: ['google-analytics', 'ga4', 'analytics', 'traffic'],
    github_url: null,
    docs_url: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: '8',
    org_id: null,
    name: 'hirelang MCP',
    slug: 'hirelang-mcp',
    description: 'AI-powered candidate screening via voice. Create screening calls, get transcripts, scores and compare candidates against job requirements.',
    category: 'hr',
    endpoint_url: 'https://mcp.mcpify.app/servers/hirelang-mcp',
    auth_type: 'api_key',
    schema_json: null,
    version: '1.0.0',
    is_public: true,
    is_verified: true,
    install_count: 3200,
    rating_avg: 4.7,
    pricing_type: 'paid',
    price_monthly: 2900,
    logo_url: null,
    tags: ['hr', 'recruiting', 'screening', 'candidates'],
    github_url: null,
    docs_url: null,
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
]
